### ISSUE TITLE
Add options to self-host mclo.gs

### ISSUE THREAD

**Issue by bigfinfrank** [aternosorg/mclogs-bukkit#3]
This is an extremely helpful utility, however in some cases (for public servers and specifically in my case, self-hosted servers), it's nice to keep everything as centralized to the owner as possible in order to maintain control. This can be especially true for server logs as (even with IPs being removed) they can hold relatively private information depending on the plugins used. For example the coordinates to a player's secret base, or the link to a private web page used by server staff that's logged to the console on server startup as a plugin is loaded.

This is why I'd like to request a configurable way to change the destination from https://mclo.gs to someone's own self-hosted instance of [aternosorg/mclogs](https://github.com/aternosorg/mclogs). *This is additionally also helpful (although not a proper solution) in combating search engine crawlers as mclo.gs is now a pretty commonly used site and I've personally had one of my uploaded logs easily findable by typing the server name in quotes into Google.*

**Comment by JulianVennen** [comment]
This has been added in v2.3.0
