### ISSUE TITLE
Config file isn't generated on startup

### ISSUE THREAD

**Issue by bigfinfrank** [aternosorg/mclogs-bukkit#4]
After updating to the latest version ([2.3.0](https://github.com/aternosorg/mclogs-bukkit/releases/tag/v2.3.0)), the configuration file wasn't created automatically (assuming that the config was new as of that update, it wasn't created in previous versions either).
I'm unable to make the folder manually as I'm not sure of the name for the folder that would be in `plugins/`, would it be `mclogs-bukkit`, `mclogs`, `Mclogs`, or something else?

**Comment by JulianVennen** [comment]
Oops, I uploaded the wrong jar which is missing some libraries.
I will release a new jar under version 2.3.1 that fixes this.

**Comment by JulianVennen** [comment]
The new version is available here: https://github.com/aternosorg/mclogs-bukkit/releases/tag/v2.3.1
I already submitted it on dev.bukkit.org but they will take a few hours to approve it
