### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by smillakoldsoe** [aternosorg/mclogs-bukkit#9]
My hexxit 2 world keeps crashing after opening it. This started when i used a builders wand. Is there anyway to fix this?

Sever crash: https://mclo.gs/GrP803K

**Comment by Soapy7261** [comment]
This not support for your minecraft server. this is support for the mclogs plugin itself

**Comment by smillakoldsoe** [comment]
> This not support for your minecraft server. this is support for the mclogs plugin itself

Do you know where i sould write then?

**Comment by Soapy7261** [comment]
You could email Aternos support@aternos.org or join the discord server https://discord.gg/aternos-107936397578489856
